default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5
  # username: postgres

development:
  <<: *default
  database: legit_research_development

test:
  <<: *default
  database: legit_research_test

production:
  <<: *default
  database: <%= ENV["MY_APP_DATABASE_DATABASE"] %>
  host: <%= ENV["MY_APP_DATABASE_HOST"] %>
  username: <%= ENV["MY_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["MY_APP_DATABASE_PASSWORD"] %>
